graph LR
A(SCM) --> B(Libs)
B --> C(Compile)
C --> D(Tests)
D --> E(Package)
E --> F(Deploy)
style A fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
style F fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
